# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchline < Formula
  desc "Streamline OpenCode plugin updates."
  homepage "https://github.com/AksharP5/Patchline"
  version "1.1.8"

  on_macos do
    on_intel do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.8/patchline_1.1.8_darwin_amd64.tar.gz"
      sha256 "c98eaa106171d721a6cd8befa63636920f6cd32f40e726adea80a70a5464d7a2"

      def install
        bin.install "patchline"
      end
    end
    on_arm do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.8/patchline_1.1.8_darwin_arm64.tar.gz"
      sha256 "3f0b451342a8d98dd556fdf38e7f8ad4a28afade9338c68fd399d1ff8024d942"

      def install
        bin.install "patchline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.8/patchline_1.1.8_linux_amd64.tar.gz"
        sha256 "9110b51b3cb605291ea7b51281607e2937be86df87b244d1a02926f82d769186"

        def install
          bin.install "patchline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.8/patchline_1.1.8_linux_arm64.tar.gz"
        sha256 "a75fa184d440620a2ee023e8a6a4b3e0ee9b8174deeb3449034998c410e52ee0"

        def install
          bin.install "patchline"
        end
      end
    end
  end
end
