# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchline < Formula
  desc "Streamline OpenCode plugin updates."
  homepage "https://github.com/AksharP5/Patchline"
  version "1.1.3"

  on_macos do
    on_intel do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.3/patchline_1.1.3_darwin_amd64.tar.gz"
      sha256 "a14775a375873c951232e43d07caab09b13f8b17fa987e883e18bb88a5ac122a"

      def install
        bin.install "patchline"
      end
    end
    on_arm do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.3/patchline_1.1.3_darwin_arm64.tar.gz"
      sha256 "d4fed6747e4a3f3f7362f25bf3c155b974a9095479b61b47c90833fe23ed32c3"

      def install
        bin.install "patchline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.3/patchline_1.1.3_linux_amd64.tar.gz"
        sha256 "0df37b97bbe65b0fcfdf553b4f54020d6d4b6c16c2678b8f89387ecc2b2e87d6"

        def install
          bin.install "patchline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.3/patchline_1.1.3_linux_arm64.tar.gz"
        sha256 "728f62b2a1231dbb17f018fc12dc223ea4799f3909460834801a044d49ed4058"

        def install
          bin.install "patchline"
        end
      end
    end
  end
end
