# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patchline < Formula
  desc "Streamline OpenCode plugin updates."
  homepage "https://github.com/AksharP5/Patchline"
  version "1.1.7"

  on_macos do
    on_intel do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.7/patchline_1.1.7_darwin_amd64.tar.gz"
      sha256 "3c3a6594e4dd1123e5a8524c8dac4da70bb886cf19de3bf8eb858a4272a73b15"

      def install
        bin.install "patchline"
      end
    end
    on_arm do
      url "https://github.com/AksharP5/Patchline/releases/download/v1.1.7/patchline_1.1.7_darwin_arm64.tar.gz"
      sha256 "358a88ff9b7c848248ace2bbe7db9536266d91a7e6ace2bf1063915339e79bef"

      def install
        bin.install "patchline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.7/patchline_1.1.7_linux_amd64.tar.gz"
        sha256 "5b4ff10bdaf228fe11dc3f9c09a79b2cd685030ff3641a854d060d351f598283"

        def install
          bin.install "patchline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AksharP5/Patchline/releases/download/v1.1.7/patchline_1.1.7_linux_arm64.tar.gz"
        sha256 "225dc284def4a8e7698198c5c10fc54e216a8b37cbefc666e9cf4a8155087682"

        def install
          bin.install "patchline"
        end
      end
    end
  end
end
